name: skin-lesion-project

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10.8

  # Scientific Computing
  - numpy<2
  - pandas
  - scikit-learn
  - scipy

  # Image Processing
  - pillow
  - opencv

  # Visualization
  - matplotlib
  - seaborn
  - plotly

  # Utilities
  - tqdm
  - pyyaml
  - ipykernel
  - tomli
  - pytest=8.4.*
  - pip

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - fastapi
      - streamlit
      - unicorn
      - timm>=1.0
      - torch==2.4.1
      - torchvision==0.19.1
      - albumentations>=2.0
      - transformers>=4.45
      - mlflow>=3.1
      - boto3
      - open-clip-torch>=2.24,<3.0
      - huggingface_hub>=0.24,<1.0
      - transformers>=4.45