name: skin-lesion-project

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10.8

  # Core ML
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  # Data
  - numpy
  - pandas
  - scikit-learn

  # Images
  - pillow
  - opencv

  # Visualization
  - matplotlib
  - plotly
  - seaborn

  # Utilities
  - tqdm
  - pyyaml
  - ipykernel
  - tomli
  - pytest=8.4.*
  - pip

  - pip:
      - timm
      - boto3
      - haversine
      - pdf2image
      - "mlflow>=3.1"
      - albumentations
      - transformers